### ISSUE TITLE
yaml 로 vm 설정

### ISSUE THREAD

**Issue by hskimsky** [HaNeul-Kim/CopyVMWareVM#3]
아래와 같이 설정 가능하도록 수정

* numvcpus 는 전체 core 개수
* `numvcpus / cpuid.coresPerSocket` 은 socket 개수가 됨
* memory 단위는 GB

```yaml
template: template79large.sky.local
displayName: hdm1
hostname: hdm1.sky.local
path: F:\vm\linux\hdp
description: >
  ZooKeeper Server
  NameNode
  ResourceManager
  HBase Master
ip: 192.168.181.211
numvcpus: 4
cpuid.coresPerSocket: 2
memsize: 8192
---
template: template79.sky.local
displayName: hdw1
hostname: hdw1.sky.local
path: F:\vm\linux\hdp
description: >
  DataNode
  NodeManager
  HBase RegionServer
ip: 192.168.181.212
numvcpus: 2
cpuid.coresPerSocket: 2
memsize: 4096
```
